[package]
name = "rm8ctl"
version = "1.0.0-SNAPSHOT"
authors = ["Bernd Vogt <bernd.vogt@sourcepit.org>"]

[profile.release]
debug = 1

[dependencies]
clap = "=2.34.0"
common_failures = "=0.1.1"
failure = "=0.1.8"
libc = "=0.2.112"
log = "=0.4.14"
stderrlog = "=0.5.1"